const tintColorLight = "#FF6B6B";
const tintColorDark = "#FF6B6B";

export default {
  light: {
    text: "#2C3E50",
    background: "#FFFFFF",
    tint: tintColorLight,
    tabIconDefault: "#95A5A6",
    tabIconSelected: tintColorLight,
    primary: "#FF6B6B",
    secondary: "#4ECDC4",
    accent: "#FFE66D",
    success: "#26D0CE",
    danger: "#FF6B6B",
    warning: "#FFD93D",
    info: "#6C5CE7",
    card: "#F8F9FA",
    border: "#E1E8ED",
    inputBackground: "#F5F7FA",
    buttonText: "#FFFFFF",
    gradient1: "#667EEA",
    gradient2: "#764BA2",
    surface: "#FFFFFF",
    surfaceLight: "#FFFFFF",
    surfaceMedium: "#F8F9FA",
    surfaceDark: "#E1E8ED",
    textSecondary: "#95A5A6",
  },
  dark: {
    text: "#FFFFFF",
    background: "#0A0E27",
    tint: tintColorDark,
    tabIconDefault: "#7F8C8D",
    tabIconSelected: tintColorDark,
    primary: "#FF6B6B",
    secondary: "#4ECDC4",
    accent: "#FFE66D",
    success: "#26D0CE",
    danger: "#FF6B6B",
    warning: "#FFD93D",
    info: "#6C5CE7",
    card: "#1A1F3A",
    border: "#2C3E50",
    inputBackground: "#151A30",
    buttonText: "#FFFFFF",
    gradient1: "#667EEA",
    gradient2: "#764BA2",
    surface: "#1A1F3A",
    surfaceLight: "#1A1F3A",
    surfaceMedium: "#151A30",
    surfaceDark: "#0A0E27",
    textSecondary: "#7F8C8D",
  },
};