name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean Install Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Build Web App
        run: |
          npx expo export --platform web --output-dir dist
        env:
          CI: true
          NODE_ENV: production

      - name: Verify Build Output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Error: dist directory not found"
            exit 1
          fi
          echo "✅ Build successful - dist directory created"
          ls -la dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: discipulapp-8d99c
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
